Device is now specified as argument 1

diff --git a/bin/upload b/bin/upload
--- a/bin/upload
+++ b/bin/upload
@@ -1,16 +1,29 @@
 #!/bin/bash
 
-#port=/dev/ttys000
-port=/dev/tty.usbserial-1410
-#port="/dev/tty.usbserial-1430"
-#port=/dev/tty.SLAB_USBtoUART
-#port="/dev/tty.wchusbserialfd130"
-#port="/dev/tty.usbserial-14130" # for Lolin D32 ESP32
+set -e
+set -u
+
+USAGE="\
+Usage: 
+  ./bin/upload DEVICE COMMAND
+Example: 
+  ./bin/upload /dev/tty.usb-1410 upload"
 
 # go back a directory if we are in the `bin` directory
 if [ "$(basename "$PWD")" = "bin" ]; then
     cd .. || exit
 fi
+
+# check that correct number of arguments are provided
+if [ ! "$#" -eq 2 ]; then
+   echo "ERROR: Incorrect number of arguments provided!"
+   echo
+   echo "$USAGE"
+   exit 1
+fi
+
+DEVICE="$1"
+COMMAND="$2"
 
 ###############################################################################
 #                              Helper Functions                               #
@@ -38,11 +51,11 @@ display_spinner()
 #                              MicroPython Flash                              #
 ###############################################################################
 
-esptool.py --port $port erase_flash 1>/dev/null &
+esptool.py --port $DEVICE erase_flash 1>/dev/null &
 display_spinner $! "Erasing ESP32 Flash Storage"
 
 esptool.py --chip esp32 \
-           --port $port \
+           --port $DEVICE \
            --baud 460800 \
            write_flash \
            --compress \
@@ -61,14 +74,14 @@ display_spinner $! "Flashing Micropython Binary"
 echo "Creating Directories"
 for dir in $(find . -not -path '*/\.*' -type d \( ! -iname ".*" \)); do
     echo "  ${dir}"
-    ampy -d 0.5 --port $port mkdir "$dir"
+    ampy -d 0.5 --port $DEVICE mkdir "$dir"
 done
 
 # Copy all Python files
 echo "Copying Python Files..."
 for file in $(find . -name \*.py); do
     echo "  ${file}"
-    ampy -d 0.5 --port $port put "$file" "$file"
+    ampy -d 0.5 --port $DEVICE put "$file" "$file"
 done
 
 
@@ -79,6 +92,6 @@ done
 # NOTE: we must set the PYTHONPATH to allow importing `config` from the parent
 # directory.
 
-id=$(ampy --port $port run bin/hwtest.py |grep chip|awk '{print $3}')
+id=$(ampy --port $DEVICE run bin/hwtest.py |grep chip|awk '{print $3}')
 echo "Machine ID is: $id"
 PYTHONPATH=. python3 bin/setgrp.py "$id"
